version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 10
  target-branch: master
  reviewers:
  - Tiryoh
  assignees:
  - Tiryoh
  labels:
  - "Type: dependencies"
  - "Lang: JavaScript"
  ignore:
  - dependency-name: electron-to-chromium
    versions:
    - 1.3.648
    - 1.3.650
    - 1.3.654
    - 1.3.655
    - 1.3.660
    - 1.3.662
    - 1.3.663
    - 1.3.665
    - 1.3.668
    - 1.3.670
    - 1.3.673
    - 1.3.675
    - 1.3.676
    - 1.3.683
    - 1.3.684
    - 1.3.688
    - 1.3.691
    - 1.3.692
    - 1.3.693
    - 1.3.696
    - 1.3.700
    - 1.3.701
    - 1.3.704
    - 1.3.707
    - 1.3.708
    - 1.3.709
    - 1.3.719
    - 1.3.720
  - dependency-name: caniuse-lite
    versions:
    - 1.0.30001179
    - 1.0.30001183
    - 1.0.30001185
    - 1.0.30001187
    - 1.0.30001191
    - 1.0.30001192
    - 1.0.30001196
    - 1.0.30001197
    - 1.0.30001198
    - 1.0.30001199
    - 1.0.30001200
    - 1.0.30001202
    - 1.0.30001204
    - 1.0.30001205
    - 1.0.30001207
    - 1.0.30001211
    - 1.0.30001214
  - dependency-name: browserslist
    versions:
    - 4.16.1
    - 4.16.3
    - 4.16.4
  - dependency-name: core-js-compat
    versions:
    - 3.10.0
    - 3.10.1
    - 3.8.3
    - 3.9.0
    - 3.9.1
  - dependency-name: core-js
    versions:
    - 3.8.3
    - 3.9.0
    - 3.9.1
  - dependency-name: vue-eslint-parser
    versions:
    - 7.4.1
    - 7.5.0
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
  commit-message:
    prefix: chore
