version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 10
  target-branch: main
  reviewers:
  - Tiryoh
  assignees:
  - Tiryoh
  labels:
  - "Type: dependencies"
  - "Lang: JavaScript"
  commit-message:
    prefix: chore
