pull_request_rules:
  - name: Automatic merge PRs from Dependabot
    conditions:
      - base=main
      - author~=^dependabot(|-preview)\[bot\]$
      - title~=bump [^\s]+ from ([\d]+)\..+ to \1\.
      - check-success=deploy/netlify
    actions:
      merge:
        method: squash
